---
development:
  cloud_name: dsxpfm6vs
  api_key: '377435857781197'
  api_secret: wlxztRuJ6TRc5ZKr-hbTWz49I8c
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dsxpfm6vs
  api_key: '377435857781197'
  api_secret: wlxztRuJ6TRc5ZKr-hbTWz49I8c
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dsxpfm6vs
  api_key: '377435857781197'
  api_secret: wlxztRuJ6TRc5ZKr-hbTWz49I8c
  enhance_image_tag: true
  static_file_support: false
